deployment:
  tasks:
    - export DEPLOYPATH=/home/username/laravel-app
    - /bin/rsync -av --exclude '.git' --exclude '.env' ./ $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/local/bin/composer install --no-dev --optimize-autoloader
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan storage:link
